# Example for numpy array

In [1]:
import pyview

In [2]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print(a)

[1 2 3 4 5 6 7]


In [3]:
b = pyview.view_nocopy(a)
print(b)

[2 3 4 5 6]


In [4]:
b[1] = 50 # instead of 3
print(a)

[ 1  2 50  4  5  6  7]
